name: Build and Push to ECR

on:
  push:
    branches:
      - main
      # - dev

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          exit-code: "0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REPO }}/my-repo:latest .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ secrets.ECR_REPO }}/my-repo:latest
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "0"

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_REPO }}/my-repo:latest
        
 