name: build and push to ecr

on:
  push:
    # pull_request:
    #   branches: ['main', 'dev']
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: trivy scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          severity: 'HIGH,CRITICAL'
          exit-code: 0

      - name: docker build image
        run: |
          docker build -t 891377154217.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .

      - name: scan image with trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: '891377154217.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest'
          format: 'table'
          exit-code: 0
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true

       - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

       
      
        
 